title = "Configuration file to load and create a CSV file of Yaak dataset properties"

[dataset]

    # ------------------------------------------------------------------------------------------------------------------
    # Dataset information
    # ------------------------------------------------------------------------------------------------------------------

    # Root path where to find the drive data
    rootpath = "/nas/drives/yaak/yaak_dataset/video_data"

    # Where to find the camera calibration files
    camera_calibration = "/nas/drives/yaak/yaak_dataset/camera_calibration"

    # Drive IDs to process, if set to "*" would read drive_ids in `rootpath`. Also:
    #   1) Drive IDs can be specified as items in a list:
    #     drive_ids = ["2021-08-13--09-27-11", "2022-01-09--09-18-46", "2021-10-13--06-30-56", "2022-01-25--14-54-13"]
    #   2) Or in a text file (one drive ID per line):
    #     drive_ids = some_path/test_drive_ids.txt
    # drive_ids = "test_drive_ids/few_samples_val.txt"
    drive_ids = ["2021-08-13--09-27-11", "2022-01-09--09-18-46", "2021-10-13--06-30-56", "2022-01-25--14-54-13"]
    # drive_ids = "test_drive_ids/drive_ids_train.txt"

    # Which camera to load, if set to "*" would ready all camera views
    camera_view = ["cam_front_center"]

    # Telemetry filename
    telemetry_filename = "metadata.json"

    # File suffix, choices "", "defish", "pii",
    suffix = "-force-key.defish"

    # File extension
    extension = "mp4"

[output]

    # Output path to store the dataset properties.
    dataset_properties_path = "output_path"

    # CSV file where the dataset properties will be stored.
    dataset_properties_filename = "yaak_dataset_properties.csv"
